"""Initial migration

Revision ID: f9ad58a0a60b
Revises: ea5283e09d12
Create Date: 2025-03-05 11:26:20.818705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9ad58a0a60b'
down_revision = 'ea5283e09d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('modify_at',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.drop_constraint('product_table_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category_table', ['product_category_id'], ['category_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_table_ibfk_1', 'category_table', ['product_category_id'], ['category_id'])

    with op.batch_alter_table('category_table', schema=None) as batch_op:
        batch_op.alter_column('modify_at',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
